### ISSUE TITLE
License incompatible with UE4

### ISSUE THREAD

**Issue by Hevedy** [darbycostello/Nav3D#9]
The GPL license isn't compatible with UE4 could be this changed to other one ?
Let's say Apache, MIT, Zlib or LGPL (where this one isn't really compatible either as this isn't an external library and is included in the engine)

Thank you

**Comment by darbycostello** [comment]
Removed license.

**Comment by Hevedy** [comment]
So what license applies now ? The public license or ?

**Comment by darbycostello** [comment]
None. There is no license at all.

**Comment by darbycostello** [comment]
I've added an MIT license. Use as you wish.
